// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "github.com/Vadim-Makhnev/url-shortener/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// URLService is an autogenerated mock type for the URLService type
type URLService struct {
	mock.Mock
}

type URLService_Expecter struct {
	mock *mock.Mock
}

func (_m *URLService) EXPECT() *URLService_Expecter {
	return &URLService_Expecter{mock: &_m.Mock}
}

// GetAllURLS provides a mock function with no fields
func (_m *URLService) GetAllURLS() ([]domain.URL, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllURLS")
	}

	var r0 []domain.URL
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.URL, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.URL); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.URL)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// URLService_GetAllURLS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllURLS'
type URLService_GetAllURLS_Call struct {
	*mock.Call
}

// GetAllURLS is a helper method to define mock.On call
func (_e *URLService_Expecter) GetAllURLS() *URLService_GetAllURLS_Call {
	return &URLService_GetAllURLS_Call{Call: _e.mock.On("GetAllURLS")}
}

func (_c *URLService_GetAllURLS_Call) Run(run func()) *URLService_GetAllURLS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *URLService_GetAllURLS_Call) Return(_a0 []domain.URL, _a1 error) *URLService_GetAllURLS_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *URLService_GetAllURLS_Call) RunAndReturn(run func() ([]domain.URL, error)) *URLService_GetAllURLS_Call {
	_c.Call.Return(run)
	return _c
}

// GetOriginalURL provides a mock function with given fields: shortCode
func (_m *URLService) GetOriginalURL(shortCode string) (string, error) {
	ret := _m.Called(shortCode)

	if len(ret) == 0 {
		panic("no return value specified for GetOriginalURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(shortCode)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(shortCode)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(shortCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// URLService_GetOriginalURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOriginalURL'
type URLService_GetOriginalURL_Call struct {
	*mock.Call
}

// GetOriginalURL is a helper method to define mock.On call
//   - shortCode string
func (_e *URLService_Expecter) GetOriginalURL(shortCode interface{}) *URLService_GetOriginalURL_Call {
	return &URLService_GetOriginalURL_Call{Call: _e.mock.On("GetOriginalURL", shortCode)}
}

func (_c *URLService_GetOriginalURL_Call) Run(run func(shortCode string)) *URLService_GetOriginalURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *URLService_GetOriginalURL_Call) Return(_a0 string, _a1 error) *URLService_GetOriginalURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *URLService_GetOriginalURL_Call) RunAndReturn(run func(string) (string, error)) *URLService_GetOriginalURL_Call {
	_c.Call.Return(run)
	return _c
}

// ShortenURL provides a mock function with given fields: originalURL
func (_m *URLService) ShortenURL(originalURL string) (*domain.URL, error) {
	ret := _m.Called(originalURL)

	if len(ret) == 0 {
		panic("no return value specified for ShortenURL")
	}

	var r0 *domain.URL
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.URL, error)); ok {
		return rf(originalURL)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.URL); ok {
		r0 = rf(originalURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.URL)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(originalURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// URLService_ShortenURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShortenURL'
type URLService_ShortenURL_Call struct {
	*mock.Call
}

// ShortenURL is a helper method to define mock.On call
//   - originalURL string
func (_e *URLService_Expecter) ShortenURL(originalURL interface{}) *URLService_ShortenURL_Call {
	return &URLService_ShortenURL_Call{Call: _e.mock.On("ShortenURL", originalURL)}
}

func (_c *URLService_ShortenURL_Call) Run(run func(originalURL string)) *URLService_ShortenURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *URLService_ShortenURL_Call) Return(_a0 *domain.URL, _a1 error) *URLService_ShortenURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *URLService_ShortenURL_Call) RunAndReturn(run func(string) (*domain.URL, error)) *URLService_ShortenURL_Call {
	_c.Call.Return(run)
	return _c
}

// NewURLService creates a new instance of URLService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewURLService(t interface {
	mock.TestingT
	Cleanup(func())
}) *URLService {
	mock := &URLService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
