// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "github.com/Vadim-Makhnev/url-shortener/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// RepositoryPostgres is an autogenerated mock type for the RepositoryPostgres type
type RepositoryPostgres struct {
	mock.Mock
}

type RepositoryPostgres_Expecter struct {
	mock *mock.Mock
}

func (_m *RepositoryPostgres) EXPECT() *RepositoryPostgres_Expecter {
	return &RepositoryPostgres_Expecter{mock: &_m.Mock}
}

// CreateURL provides a mock function with given fields: shortCode, originalURL
func (_m *RepositoryPostgres) CreateURL(shortCode string, originalURL string) (*domain.URL, error) {
	ret := _m.Called(shortCode, originalURL)

	if len(ret) == 0 {
		panic("no return value specified for CreateURL")
	}

	var r0 *domain.URL
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*domain.URL, error)); ok {
		return rf(shortCode, originalURL)
	}
	if rf, ok := ret.Get(0).(func(string, string) *domain.URL); ok {
		r0 = rf(shortCode, originalURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.URL)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(shortCode, originalURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryPostgres_CreateURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateURL'
type RepositoryPostgres_CreateURL_Call struct {
	*mock.Call
}

// CreateURL is a helper method to define mock.On call
//   - shortCode string
//   - originalURL string
func (_e *RepositoryPostgres_Expecter) CreateURL(shortCode interface{}, originalURL interface{}) *RepositoryPostgres_CreateURL_Call {
	return &RepositoryPostgres_CreateURL_Call{Call: _e.mock.On("CreateURL", shortCode, originalURL)}
}

func (_c *RepositoryPostgres_CreateURL_Call) Run(run func(shortCode string, originalURL string)) *RepositoryPostgres_CreateURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *RepositoryPostgres_CreateURL_Call) Return(_a0 *domain.URL, _a1 error) *RepositoryPostgres_CreateURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryPostgres_CreateURL_Call) RunAndReturn(run func(string, string) (*domain.URL, error)) *RepositoryPostgres_CreateURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllURLS provides a mock function with no fields
func (_m *RepositoryPostgres) GetAllURLS() ([]domain.URL, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllURLS")
	}

	var r0 []domain.URL
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.URL, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.URL); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.URL)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryPostgres_GetAllURLS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllURLS'
type RepositoryPostgres_GetAllURLS_Call struct {
	*mock.Call
}

// GetAllURLS is a helper method to define mock.On call
func (_e *RepositoryPostgres_Expecter) GetAllURLS() *RepositoryPostgres_GetAllURLS_Call {
	return &RepositoryPostgres_GetAllURLS_Call{Call: _e.mock.On("GetAllURLS")}
}

func (_c *RepositoryPostgres_GetAllURLS_Call) Run(run func()) *RepositoryPostgres_GetAllURLS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RepositoryPostgres_GetAllURLS_Call) Return(_a0 []domain.URL, _a1 error) *RepositoryPostgres_GetAllURLS_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryPostgres_GetAllURLS_Call) RunAndReturn(run func() ([]domain.URL, error)) *RepositoryPostgres_GetAllURLS_Call {
	_c.Call.Return(run)
	return _c
}

// GetURLByShortCode provides a mock function with given fields: shortCode
func (_m *RepositoryPostgres) GetURLByShortCode(shortCode string) (string, error) {
	ret := _m.Called(shortCode)

	if len(ret) == 0 {
		panic("no return value specified for GetURLByShortCode")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(shortCode)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(shortCode)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(shortCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryPostgres_GetURLByShortCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURLByShortCode'
type RepositoryPostgres_GetURLByShortCode_Call struct {
	*mock.Call
}

// GetURLByShortCode is a helper method to define mock.On call
//   - shortCode string
func (_e *RepositoryPostgres_Expecter) GetURLByShortCode(shortCode interface{}) *RepositoryPostgres_GetURLByShortCode_Call {
	return &RepositoryPostgres_GetURLByShortCode_Call{Call: _e.mock.On("GetURLByShortCode", shortCode)}
}

func (_c *RepositoryPostgres_GetURLByShortCode_Call) Run(run func(shortCode string)) *RepositoryPostgres_GetURLByShortCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *RepositoryPostgres_GetURLByShortCode_Call) Return(_a0 string, _a1 error) *RepositoryPostgres_GetURLByShortCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryPostgres_GetURLByShortCode_Call) RunAndReturn(run func(string) (string, error)) *RepositoryPostgres_GetURLByShortCode_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepositoryPostgres creates a new instance of RepositoryPostgres. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryPostgres(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryPostgres {
	mock := &RepositoryPostgres{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
