// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RepositoryRedis is an autogenerated mock type for the RepositoryRedis type
type RepositoryRedis struct {
	mock.Mock
}

type RepositoryRedis_Expecter struct {
	mock *mock.Mock
}

func (_m *RepositoryRedis) EXPECT() *RepositoryRedis_Expecter {
	return &RepositoryRedis_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, shortCode
func (_m *RepositoryRedis) Get(ctx context.Context, shortCode string) (string, error) {
	ret := _m.Called(ctx, shortCode)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, shortCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, shortCode)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shortCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryRedis_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type RepositoryRedis_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - shortCode string
func (_e *RepositoryRedis_Expecter) Get(ctx interface{}, shortCode interface{}) *RepositoryRedis_Get_Call {
	return &RepositoryRedis_Get_Call{Call: _e.mock.On("Get", ctx, shortCode)}
}

func (_c *RepositoryRedis_Get_Call) Run(run func(ctx context.Context, shortCode string)) *RepositoryRedis_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RepositoryRedis_Get_Call) Return(_a0 string, _a1 error) *RepositoryRedis_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryRedis_Get_Call) RunAndReturn(run func(context.Context, string) (string, error)) *RepositoryRedis_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, shortCode, originalURL
func (_m *RepositoryRedis) Set(ctx context.Context, shortCode string, originalURL string) error {
	ret := _m.Called(ctx, shortCode, originalURL)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, shortCode, originalURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RepositoryRedis_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type RepositoryRedis_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - shortCode string
//   - originalURL string
func (_e *RepositoryRedis_Expecter) Set(ctx interface{}, shortCode interface{}, originalURL interface{}) *RepositoryRedis_Set_Call {
	return &RepositoryRedis_Set_Call{Call: _e.mock.On("Set", ctx, shortCode, originalURL)}
}

func (_c *RepositoryRedis_Set_Call) Run(run func(ctx context.Context, shortCode string, originalURL string)) *RepositoryRedis_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *RepositoryRedis_Set_Call) Return(_a0 error) *RepositoryRedis_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryRedis_Set_Call) RunAndReturn(run func(context.Context, string, string) error) *RepositoryRedis_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepositoryRedis creates a new instance of RepositoryRedis. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryRedis(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryRedis {
	mock := &RepositoryRedis{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
